### ISSUE TITLE
on_enter_normal_mode is called on every normal mode command

### ISSUE THREAD

**Issue by esthermations** [chr-1x/4vim#7]
I'm not sure if this is intended or not.

Basic repro steps:
- Add `fprintf(stderr, "Entered normal mode.\n");` to your `on_enter_normal_mode()` function.
- Re-compile and run the program.
- Enter normal mode.
- Press `j`, `k`, whatever. Every single time you press it, the message is printed to stderr.

If this is intended, maybe it should be called something other than on_**enter**_normal_mode.

**Comment by chr-1x** [comment]
Thanks for the feedback. The vim layer is a little aggressive about calling an internal function called `enter_normal_mode` because it's a good way to reset to a known good state with appropriate keymaps and such. In particular, it's called every time a movement (particularly movements that are bound to chords) would potentially result in an action, like deleting or yanking, to reset out of the chord's keymap once the action is complete. Since this breaks the mental model of how vim works, I've modified the vim layer to call the user callback only if the editor was not previously in normal mode at the time `enter_normal_mode` is called. I believe this fixes the problem, I'm now seeing the callback only called when re-entering normal mode from visual, insert, or replace mode.
